version: "3.8"
services:

  edge-service:
    depends_on:
      - catalog-service
      - order-service
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testData
      - ORDER_SERVICE_URL=http://order-service:9002
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  # Catalog service
  catalog-service:
    depends_on:
      - polar-postgres
      - config-server
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testData
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  # Catalog service
  order-service:
    depends_on:
      - polar-postgres
      - config-server
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - POLAR_CATALOG_SERVICE_URI=http://localhost:9001/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order

  # Config service
  config-server:
    image: "config-server"
    container_name: "config-server"
    ports:
      - 8888:8888
      - 9888:9888

  # Backing Services
  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    #      - POSTGRES_DB=polardb_catalog
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql